runs:
  using: "composite"
  steps:
    - name: Install Templates
      run: |
        dotnet new --install ./BepInEx.Templates/templates/
      shell: bash
    
    - name: Test BepInEx6 .NET Core Template
      if: always()
      run: |
        mkdir -p temp-test
        cd temp-test
        dotnet new bep6resonite --dry-run --diagnostics
      shell: bash