name: Verify Templates

on:
  push:
  pull_request:
  
jobs:
  test-sdk9:
    name: Test .NET SDK 9
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup .NET env
        uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: 9.x

      - run: |
          dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }}

      - name: Dry-run Templates
        uses: ./.github/actions/dryrun-templates