# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "{authors}" # Change this to the team you're uploading the mod to on Thunderstore
name = "ProjectName" # Change this to your mod's name, no spaces or special characters, max 128 characters
versionNumber = "{version}" # Change this to your mod's version, must be in semantic versioning format (e.g. 1.0.0, 2.1.3, 0.1.0-alpha.1)
description = "Example mod description" # Change this to your mod's description, max 250 characters
websiteUrl = "" # Change this to your mod's website/repository, or leave blank
containsNsfwContent = false

[package.dependencies] 
# List any dependencies your mod has here, in the format "namespace/mod-name" = "version-constraint"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]
categories = [] # Categories this mod will be listed under (slugs from https://thunderstore.io/api/experimental/community/resonite/category/)
